### ISSUE TITLE
[BUG] If you try to open a quest with a missing user you get an error

### ISSUE THREAD

**Issue by xdy** [death-save/foundryvtt-forien-quest-log#3]
**Module Version:** v0.5.2

**Describe the bug**
You get a null pointer on line 375 of modules/entities/quest.mjs

**To Reproduce**
Create a personal quest for a user.
Remove the user.
Try to click the quest log button, get a null pointer as per above, and the quest log ui doesn't open

**Expected behavior**
No null pointer, the ui should open.

**Screenshots**
-

**Browser:**
 - 

**Foundry Version:** 
0.7.7

**Game System:** 
Twodsix (but any should work)

**Additional context**
https://github.com/death-save/foundryvtt-forien-quest-log/pull/2 fixes this.

**Comment by eclarke12** [comment]
Fixed with https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/pull/2
